### ISSUE TITLE
Panic when excluding fluentd

### ISSUE THREAD

**Issue by lander2k2** [banzaicloud/logging-operator#871]
**Describe the bug**:
When I submit a Logging resource with `spec.fluentd` omitted, the controller manger panics

**Expected behaviour**:
For the logging operator to deploy fluent-bit only.

**Steps to reproduce the bug**:
1. remove the `spec.fluentd` block from a Logging manifest and create it.

**Additional context**:
none

**Environment details**:
- Kubernetes version: v1.19.7
- Cloud-provider/provisioner: AWS
- logging-operator version: 3.15.0
- Install method: Helm
- Logs from the controller:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b0 pc=0x15d2d31]

goroutine 525 [running]:
github.com/banzaicloud/logging-operator/pkg/sdk/api/v1beta1.(*Logging).SetDefaults(0xc000d894a0, 0x1bea078, 0xc000853b90)
        /workspace/pkg/sdk/api/v1beta1/logging_types.go:295 +0x691
github.com/banzaicloud/logging-operator/controllers.(*LoggingReconciler).Reconcile(0xc0000becc0, 0x1bea078, 0xc000853b90, 0x0
, 0x0, 0xc000875ec0, 0xf, 0xc000853b90, 0xc000030000, 0x186b040, ...)
        /workspace/controllers/logging_controller.go:84 +0x245
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00023d040, 0x1be9fd0, 0xc0002e3b80,
0x182b5a0, 0xc000bfe220)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00023d040, 0x1be9fd0, 0xc0002e3b8
0, 0xc00092bf00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0004942d0, 0xc00023d040, 0x1be9fd0, 0xc
0002e3b80)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:210 +0x425
```

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: bug-example
spec:
  controlNamespace: logging-system
  fluentbit: {}
```

/kind bug

**Comment by lander2k2** [comment]
New error was due to fluentd values being referenced for fluentbit's config secret.  That has also been addressed in the linked PR.
